name: Changelog
on:
  # Trigger the workflow on pushes to only the 'hotfix' and 'release' branches
  push:
    branches:
      - hotfix/*
      - release/*
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

jobs:
  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      # Set environment variables
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"

          echo "::set-output name=version::$VERSION"

      # Generate a changelog
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1.1.7
        id: git-cliff
        with:
          config: .github/changelog/cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GIT_CLIFF_TAG: "${{ steps.properties.outputs.version }}"

      # Print the changelog
      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      # Create pull request
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'Milad Nekofar'
          git config user.email 'nekofar@users.noreply.github.com'
          git checkout -B update-changelog-`date +%s`
          git commit -am "docs(changelog): update the changelog file" -m "[skip ci]"
          gh pr create \
            --title "docs(changelog): update the changelog file" \
            --body "Current pull request contains patched `CHANGELOG.md` file." \
            --label documentation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
